Repository Gobongbab/Festamate-Server, pull requests merged in 2025-04, with the labels that each got.

#79 CORS 설정 추가
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#80 CORS 헤더 명시 및 JWT 유효기간 연장
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#83 로깅 및 알림 시스템을 구축합니다.
  build.gradle
  src/main/java/com/gobongbob/festamate/Test.java
  src/main/resources/application.yml
Labels: 🌏 Deploy, 🌐 Infra

#85 STOMP를 활용한 실시간 채팅 기능 구현
  src/main/java/com/gobongbob/festamate/domain/chat/application/ChatService.java
  src/main/java/com/gobongbob/festamate/domain/chat/domain/ChatRoom.java
  src/main/java/com/gobongbob/festamate/domain/chat/domain/Message.java
  src/main/java/com/gobongbob/festamate/domain/chat/dto/request/MessageRequest.java
  src/main/java/com/gobongbob/festamate/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/gobongbob/festamate/domain/chat/dto/response/MessageResponse.java
  src/main/java/com/gobongbob/festamate/domain/chat/persistence/ChatRepository.java
  src/main/java/com/gobongbob/festamate/domain/chat/persistence/ChatRoomRepository.java
  src/main/java/com/gobongbob/festamate/domain/chat/persistence/MessageRepository.java
  src/main/java/com/gobongbob/festamate/domain/chat/presentation/ChatController.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
  src/main/java/com/gobongbob/festamate/domain/report/domain/ReportReason.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/global/config/WebSocketConfig.java
  src/main/java/com/gobongbob/festamate/global/config/WebSocketErrorHandler.java
  src/main/java/com/gobongbob/festamate/global/config/WebSocketInterceptor.java
Labels: ✨ Feature

#91 Spring Boot의 Forward Header 활성화
  src/main/resources/application.yml
Labels: 🐞 BugFix, ✨ Feature

#99 소그인 에러 수정
  build.gradle
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/domain/CustomMemberDetails.java
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/domain/MinimalMemberDetails.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/presentation/OauthController.java
  src/main/java/com/gobongbob/festamate/domain/image/domain/ProfileImage.java
  src/main/java/com/gobongbob/festamate/domain/image/infrastructure/ProfileImageInitializer.java
  src/main/java/com/gobongbob/festamate/domain/image/persistence/ProfileImageRepository.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/MemberExistRequest.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/gobongbob/festamate/domain/member/persistence/MemberRepository.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Room.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/ParticipationWithFriendRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/RoomCreateRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/RoomUpdateRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/MemberExistResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomListResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
  src/main/java/com/gobongbob/festamate/global/util/TokenProvider.java
  src/main/java/com/gobongbob/festamate/testUser/TestService.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#106 프로필 등록 시 랜덤 닉네임 생성하도록 수정합니다.
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/ProfileRegisterRequest.java
Labels: ✨ Feature

#109 프로필 수정(닉네임 수정) 기능을 수정합니다.
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/MemberNicknameRequest.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
Labels: 🔨 Refactor

#115 소그인 로직 개선
  build.gradle
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/dto/request/KakaoUserInfo.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/dto/request/LoginRequest.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/dto/request/LoginWithKakaoRequest.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/dto/response/KakaoCheckResponse.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/dto/response/KakaoTokenResponse.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/presentation/OauthController.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/ProfileRegisterRequest.java
  src/main/java/com/gobongbob/festamate/domain/member/persistence/MemberRepository.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
  src/main/java/com/gobongbob/festamate/global/config/WebClientConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenProvider.java
Labels: ✨ Feature, 🔨 Refactor

#116 record에서 불필요한 어노테이션 제거
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/application/TokenService.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/presentation/OauthController.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/ProfileRegisterRequest.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
  src/main/java/com/gobongbob/festamate/global/util/TokenProvider.java
Labels: 🐞 BugFix

#119 프로필 등록 API 경로 추가
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
Labels: 🐞 BugFix

#120 사용자 정보 저장 시 트랜잭션 처리
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
Labels: 🐞 BugFix

#122 기존 회원 로그인 시 JWT 리턴하도록 개선
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/presentation/OauthController.java
Labels: 🐞 BugFix

#125 CD 진행 중 발생한 에러 해결을 위해 누락된 코드 수정
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
Labels: 🐞 BugFix

#127 소그인 JWT 서명 오류 해결
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/application/CustomMemberDetailsService.java
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/application/TokenService.java
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/domain/TokenType.java
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/presentation/TokenController.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/presentation/OauthController.java
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
  src/main/java/com/gobongbob/festamate/global/util/TokenProvider.java
  src/main/java/com/gobongbob/festamate/testUser/TestService.java
Labels: 🐞 BugFix

#128 loadUserByUsername에서 loginId를 사용하도록 변경
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/application/CustomMemberDetailsService.java
Labels: 🐞 BugFix

#129 카카오 로그인 반환값을 Map으로 변경
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
Labels: 🐞 BugFix

#126 FK로 인한 엔티티 삭제 불가 문제 해결
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/application/CustomMemberDetailsService.java
  src/main/java/com/gobongbob/festamate/domain/chat/persistence/ChatRoomRepository.java
  src/main/java/com/gobongbob/festamate/domain/chat/persistence/MessageRepository.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/gobongbob/festamate/domain/member/persistence/MemberRepository.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/persistence/RoomRepository.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomParticipantRepository.java
  src/main/java/com/gobongbob/festamate/testUser/TestService.java
Labels: 🐞 BugFix

#130 스웨거를 도입합니다.
  build.gradle
  src/main/java/com/gobongbob/festamate/domain/admin/presentation/AdminController.java
  src/main/java/com/gobongbob/festamate/domain/chat/presentation/ChatController.java
  src/main/java/com/gobongbob/festamate/domain/coupon/presentation/CouponController.java
  src/main/java/com/gobongbob/festamate/domain/image/presentation/OcrController.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
  src/main/java/com/gobongbob/festamate/domain/report/presentation/ReportController.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/config/SwaggerConfig.java
  src/main/java/com/gobongbob/festamate/global/response/ResponseCode.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
Labels: ✨ Feature, 🔨 Refactor

#134 카카오 소셜로그인 및 프로필 연동 로직 안정화
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/application/OauthService.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/dto/request/KakaoUserInfo.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/dto/response/KakaoTokenResponse.java
  src/main/java/com/gobongbob/festamate/domain/auth/oauth/presentation/OauthController.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/ProfileUpdateRequest.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#135 소그인 허용 경로 추가
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
Labels: 🐞 BugFix

#146 인증 코드 유효 시간을 100일로 수정
  src/main/java/com/gobongbob/festamate/domain/sms/application/TokyoSnsService.java
Labels: ✅ Test

#149 시큐리티 경로 수정
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
Labels: 🐞 BugFix, 🌐 Infra

#153 Redis 설정 추가
  build.gradle
  docker-compose-dev.yml
  src/main/java/com/gobongbob/festamate/domain/sms/application/TokyoSnsService.java
  src/main/java/com/gobongbob/festamate/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐋 Docker, 🔨 Refactor

#157 docker-compose 이용하여 Redis 컨테이너도 올리기
  .github/workflows/cd-dev.yml
  docker-compose-dev.yml
Labels: 🔨 Refactor

#159 모니터링 시스템을 구축합니다.
  build.gradle
  src/main/java/com/gobongbob/festamate/Test.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ✨ Feature, 🌐 Infra

#163 Redis 호스트 이름 수정
  docker-compose-dev.yml
  src/main/java/com/gobongbob/festamate/FestamateApplication.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/sms/application/TokyoSnsService.java
  src/main/java/com/gobongbob/festamate/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐞 BugFix, 🗃 Database, 🐋 Docker, 🔨 Refactor

#170 SecurityConfig 내 학생증 인증 경로 추가
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
Labels: 🐞 BugFix

#174 프로필 등록 시 학번 중복 예외 처리 구현
  src/main/resources/application.yml
Labels: 🐞 BugFix

#175 모임방 매칭 완료 전환 기능 구현
  src/main/java/com/gobongbob/festamate/domain/chat/application/ChatService.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/FriendPhoneNumbersRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomApi.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/global/response/ResponseCode.java
  src/main/java/com/gobongbob/festamate/testUser/TestService.java
  src/test/java/com/gobongbob/festamate/common/fixture/MemberFixture.java
  src/test/java/com/gobongbob/festamate/common/fixture/RoomFixture.java
  src/test/java/com/gobongbob/festamate/domain/member/application/MemberServiceTest.java
  src/test/java/com/gobongbob/festamate/domain/room/application/RoomServiceTest.java
  src/test/java/com/gobongbob/festamate/domain/room/domain/RoomTest.java
Labels: 🐞 BugFix, ✨ Feature

#177 모임 상세 조회 DTO에 회원 권한 필드 추가
  src/main/java/com/gobongbob/festamate/domain/coupon/application/CouponService.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/ParticipantRole.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Role.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/RoomAuthority.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/RoomParticipant.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/persistence/RoomParticipantRepository.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomApi.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
  src/main/resources/data.sql
  src/test/java/com/gobongbob/festamate/common/fixture/RoomParticipantFixture.java
  src/test/java/com/gobongbob/festamate/domain/room/application/RoomServiceTest.java
Labels: ✨ Feature

#185 일부 테이블 칼럼 변경에 따른 DB 테이블 재생성
  src/main/resources/data.sql
Labels: 🐞 BugFix

#188 모임 생성 시, 정원에 따라 친구 참여를 강제하는 로직 추가
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Room.java
Labels: ✨ Feature

#182 관리자 기능 구체화
  src/main/java/com/gobongbob/festamate/domain/admin/presentation/AdminController.java
  src/main/java/com/gobongbob/festamate/domain/auth/jwt/domain/CustomMemberDetails.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Role.java
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenProvider.java
  src/main/java/com/gobongbob/festamate/testUser/TestService.java
  src/test/java/com/gobongbob/festamate/common/fixture/MemberFixture.java
  src/test/java/com/gobongbob/festamate/domain/member/application/MemberServiceTest.java
Labels: ✨ Feature

#194 테스트 유저 생성시 중복없이 생성되도록 수정합니다.
  src/main/java/com/gobongbob/festamate/testUser/TestService.java
  src/main/resources/data.sql
Labels: 🔨 Refactor

#199 모임의 성별 조건과 관계없이 입장할 수 있는 오류 수정
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
  src/main/java/com/gobongbob/festamate/global/response/ResponseCode.java
Labels: 🐞 BugFix, 🔨 Refactor

#204 모임방 상세조회 수정
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomResponse.java
Labels: 🔨 Refactor
