Repository Gobongbab/Festamate-Server, pull requests merged in 2025-03, with the labels that each got.

#21 모임방 관련 CRUD API 구현
  src/main/java/com/gobongbob/festamate/domain/member/domain/Gender.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Room.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/RoomCreateRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/RoomUpdateRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/persistence/RoomRepository.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/test/java/com/gobongbob/festamate/domain/room/application/RoomServiceTest.java
  src/test/java/com/gobongbob/festamate/domain/room/domain/RoomTest.java
  src/test/java/com/gobongbob/festamate/domain/room/fixture/RoomFixture.java
  src/test/java/com/gobongbob/festamate/serviceSliceTest.java
  src/test/resources/application.yml
Labels: ✨ Feature, ✅ Test

#26 CD 스크립트 테스트
  .github/workflows/cd.yml
  docker-compose-dev.yml
  src/main/java/com/gobongbob/festamate/Test.java
  src/main/resources/application.yml
Labels: 🌐 CI/CD

#30 워크플로우 테스트
  .github/workflows/cd.yml
  docker-compose-dev.yml
  src/main/resources/application.yml
Labels: 🌐 CI/CD, ✅ Test

#35 학생증 인증 기능 구현
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  docker-compose-dev.yml
  src/main/java/com/gobongbob/festamate/domain/image/application/OcrService.java
  src/main/java/com/gobongbob/festamate/domain/image/dto/response/StudentInfoResponse.java
  src/main/java/com/gobongbob/festamate/domain/image/presentation/OcrController.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ✨ Feature

#37 게시글 신고 기능 구현
  src/main/java/com/gobongbob/festamate/domain/report/application/ReportService.java
  src/main/java/com/gobongbob/festamate/domain/report/domain/Report.java
  src/main/java/com/gobongbob/festamate/domain/report/domain/ReportReason.java
  src/main/java/com/gobongbob/festamate/domain/report/dto/request/ReportRoomRequest.java
  src/main/java/com/gobongbob/festamate/domain/report/dto/response/ReportRoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/report/persistence/ReportRepository.java
  src/main/java/com/gobongbob/festamate/domain/report/presentation/ReportController.java
Labels: ✨ Feature

#39 모임에 참여중인 회원 관련 기능 구현
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Room.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/RoomParticipant.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomParticipantRepository.java
  src/main/java/com/gobongbob/festamate/domain/roomParticipant/domain/RoomParticipant.java
  src/test/java/com/gobongbob/festamate/common/builder/BuilderSupporter.java
  src/test/java/com/gobongbob/festamate/common/builder/TestFixtureBuilder.java
  src/test/java/com/gobongbob/festamate/common/fixture/RoomParticipantFixture.java
  src/test/java/com/gobongbob/festamate/domain/room/application/RoomServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#44 운영용 EC2에 앱 서버를 배포하도록 CD 스크립트 수정
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .gitignore
  Dockerfile.prod
  docker-compose-prod.yml
Labels: 🌐 CI/CD

#45 main 브랜치에 merge를 해봅니다.
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
  .gitignore
  Dockerfile.dev
  Dockerfile.prod
  README.md
  build.gradle
  docker-compose-dev.yml
  docker-compose-prod.yml
  src/main/java/com/gobongbob/festamate/FestamateApplication.java
  src/main/java/com/gobongbob/festamate/Test.java
  src/main/java/com/gobongbob/festamate/domain/department/domain/Department.java
  src/main/java/com/gobongbob/festamate/domain/image/application/OcrService.java
  src/main/java/com/gobongbob/festamate/domain/image/dto/response/StudentInfoResponse.java
  src/main/java/com/gobongbob/festamate/domain/image/presentation/OcrController.java
  src/main/java/com/gobongbob/festamate/domain/major/domain/Major.java
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Gender.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/MemberCreateRequest.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/response/MemberResponse.java
  src/main/java/com/gobongbob/festamate/domain/member/persistence/MemberRepository.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
  src/main/java/com/gobongbob/festamate/domain/report/application/ReportService.java
  src/main/java/com/gobongbob/festamate/domain/report/domain/Report.java
  src/main/java/com/gobongbob/festamate/domain/report/domain/ReportReason.java
  src/main/java/com/gobongbob/festamate/domain/report/dto/request/ReportRoomRequest.java
  src/main/java/com/gobongbob/festamate/domain/report/dto/response/ReportRoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/report/persistence/ReportRepository.java
  src/main/java/com/gobongbob/festamate/domain/report/presentation/ReportController.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Room.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/RoomParticipant.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/RoomCreateRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/request/RoomUpdateRequest.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/persistence/RoomRepository.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomParticipantRepository.java
  src/main/java/com/gobongbob/festamate/domain/roomParticipant/domain/RoomParticipant.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/gobongbob/festamate/common/builder/BuilderSupporter.java
  src/test/java/com/gobongbob/festamate/common/builder/TestFixtureBuilder.java
  src/test/java/com/gobongbob/festamate/common/fixture/MemberFixture.java
  src/test/java/com/gobongbob/festamate/common/fixture/RoomFixture.java
  src/test/java/com/gobongbob/festamate/common/fixture/RoomParticipantFixture.java
  src/test/java/com/gobongbob/festamate/domain/member/application/MemberServiceTest.java
  src/test/java/com/gobongbob/festamate/domain/room/application/RoomServiceTest.java
  src/test/java/com/gobongbob/festamate/domain/room/domain/RoomTest.java
  src/test/java/com/gobongbob/festamate/serviceSliceTest.java
  src/test/resources/application.yml
Labels: 🌐 CI/CD, ✅ Test

#50 채팅 관련 엔티티 구현 및 기본적인 채팅 기능 구현
  build.gradle
  src/main/java/com/gobongbob/festamate/domain/chat/application/ChatService.java
  src/main/java/com/gobongbob/festamate/domain/chat/domain/Chat.java
  src/main/java/com/gobongbob/festamate/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/gobongbob/festamate/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/gobongbob/festamate/domain/chat/persistence/ChatRepository.java
  src/main/java/com/gobongbob/festamate/domain/chat/presentation/ChatController.java
  src/main/java/com/gobongbob/festamate/domain/chatRoom/domain/ChatRoom.java
  src/main/java/com/gobongbob/festamate/domain/chatRoom/repository/ChatRoomRepository.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/global/config/WebSocketConfig.java
  src/main/java/com/gobongbob/festamate/global/config/WebSocketInterceptor.java
Labels: ✨ Feature

#52 Feat/#49
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .gitignore
  Dockerfile.prod
  docker-compose-prod.yml
  src/main/java/com/gobongbob/festamate/domain/chat/application/ChatService.java
  src/main/java/com/gobongbob/festamate/domain/chat/domain/Chat.java
  src/main/java/com/gobongbob/festamate/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/gobongbob/festamate/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/gobongbob/festamate/domain/chat/persistence/ChatRepository.java
  src/main/java/com/gobongbob/festamate/domain/chat/presentation/ChatController.java
  src/main/java/com/gobongbob/festamate/domain/chatRoom/domain/ChatRoom.java
  src/main/java/com/gobongbob/festamate/domain/chatRoom/repository/ChatRoomRepository.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomParticipationService.java
  src/main/java/com/gobongbob/festamate/domain/room/application/RoomService.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Room.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/RoomParticipant.java
  src/main/java/com/gobongbob/festamate/domain/room/dto/response/RoomResponse.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomController.java
  src/main/java/com/gobongbob/festamate/domain/room/presentation/RoomParticipantRepository.java
  src/main/java/com/gobongbob/festamate/global/config/WebSocketConfig.java
  src/main/java/com/gobongbob/festamate/global/config/WebSocketInterceptor.java
  src/test/java/com/gobongbob/festamate/common/builder/BuilderSupporter.java
  src/test/java/com/gobongbob/festamate/common/builder/TestFixtureBuilder.java
  src/test/java/com/gobongbob/festamate/common/fixture/RoomParticipantFixture.java
  src/test/java/com/gobongbob/festamate/domain/room/application/RoomServiceTest.java
Labels: ✨ Feature

#40 알림 기능 구현 및 CD 스크립트 수정
  .github/workflows/cd-dev.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/global/NotificationService.java
  src/main/java/com/gobongbob/festamate/global/config/FirebaseConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#54 fix: 빌드 테스트 에러 수정
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
Labels: 🐞 BugFix

#60 CD 스크립트의 빌드 테스트 에러 수정
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  src/main/java/com/gobongbob/festamate/global/config/FirebaseConfig.java
  src/main/java/com/gobongbob/festamate/global/config/SecurityConfig.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
  src/main/resources/application.yml
Labels: 🐞 BugFix, 🌐 CI/CD

#69 프로필 등록 기능 구현
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/member/dto/request/ProfileRegisterRequest.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
Labels: ✨ Feature

#73 닉네임 중복 체크 기능 구현
  src/main/java/com/gobongbob/festamate/domain/member/application/MemberService.java
  src/main/java/com/gobongbob/festamate/domain/member/persistence/MemberRepository.java
  src/main/java/com/gobongbob/festamate/domain/member/presentation/MemberController.java
  src/main/java/com/gobongbob/festamate/global/util/TokenAuthenticationFilter.java
Labels: ✨ Feature
