Repository Gobongbab/Festamate-Server, pull requests merged in 2025-02, with the labels that each got.

#2 기본 엔티티 구현
  src/main/java/com/gobongbob/festamate/domain/ban/domain/Ban.java
  src/main/java/com/gobongbob/festamate/domain/department/domain/Department.java
  src/main/java/com/gobongbob/festamate/domain/image/domain/Image.java
  src/main/java/com/gobongbob/festamate/domain/image/domain/ProfileImage.java
  src/main/java/com/gobongbob/festamate/domain/image/domain/RoomImage.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Gender.java
  src/main/java/com/gobongbob/festamate/domain/member/domain/Member.java
  src/main/java/com/gobongbob/festamate/domain/report/domain/Report.java
  src/main/java/com/gobongbob/festamate/domain/room/domain/Room.java
  src/main/java/com/gobongbob/festamate/domain/roomParticipant/domain/RoomParticipant.java
Labels: ✨ Feature

#6 개발 환경용 Docker 설정
  Dockerfile.dev
  docker-compose-dev.yml
Labels: 🐋 Docker

#10 CI 스크립트 빌드 실패 오류 수정
  Dockerfile-dev
Labels: 🐞 BugFix, 🌐 CI/CD

#13 application.yml에 기본적인 DB 세팅
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🗃 Database

#14 ci 스크립트 수정
  .github/workflows/ci.yml
  Dockerfile.dev
  docker-compose-dev.yml
Labels: 🐞 BugFix, 🌐 CI/CD

#19 feat: CD 스크립트 추가
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  docker-compose-dev.yml
  src/main/resources/application.yml
Labels: 🌐 CI/CD

#20 test: CI/CD 스크립트
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  docker-compose-dev.yml
  src/main/java/com/gobongbob/festamate/Test.java
Labels: 🌐 CI/CD
